title: Fresh Delights Catering
description: 'A Healthy Catering Company in Hinckley '
social_link: twitter/Freshhealthy17
social_username: freshdelights17
github_repo: athena
github_username: broccolini
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /Fresh Delights Catering
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
